# Define here the models for your scraped items
#
# See documentation in:
# https://docs.scrapy.org/en/latest/topics/items.html

import scrapy


class SpiderGsmarenaItem(scrapy.Item):
    # define the fields for your item here like:
    # name = scrapy.Field()
    brand = scrapy.Field()
    model_name = scrapy.Field()
    network_technology = scrapy.Field()
    net2g = scrapy.Field()
    net3g = scrapy.Field()
    net4g = scrapy.Field()
    net5g = scrapy.Field()
    speed = scrapy.Field()
    announced_date = scrapy.Field()
    status = scrapy.Field()
    body_dimensions = scrapy.Field()
    weight = scrapy.Field()
    build = scrapy.Field()
    sim = scrapy.Field()
    body_other = scrapy.Field()
    display_type = scrapy.Field()
    display_size = scrapy.Field()
    display_resolution = scrapy.Field()
    display_protection = scrapy.Field()
    display_other = scrapy.Field()
    platform_os = scrapy.Field()
    chipset = scrapy.Field()
    cpu = scrapy.Field()
    gpu = scrapy.Field()
    memorycard_slot = scrapy.Field()
    internal_memory = scrapy.Field()
    memory_other = scrapy.Field()
    camera1_type = scrapy.Field()
    camera1_modules = scrapy.Field()
    camera1_features = scrapy.Field()
    camera1_video = scrapy.Field()
    camera2_type = scrapy.Field()
    camera2_modules = scrapy.Field()
    camera2_features = scrapy.Field()
    camera2_video = scrapy.Field()
    loudspeaker = scrapy.Field()
    mm35_jack = scrapy.Field()
    wlan = scrapy.Field()
    bluetooth = scrapy.Field()
    gps = scrapy.Field()
    nfc = scrapy.Field()
    radio = scrapy.Field()
    usb = scrapy.Field()
    sensors = scrapy.Field()
    features_other = scrapy.Field()
    battery_type = scrapy.Field()
    charging = scrapy.Field()
    colors = scrapy.Field()
    models = scrapy.Field()
    sar = scrapy.Field()
    sar_eu = scrapy.Field()
    price = scrapy.Field()
    test_performance = scrapy.Field()
    test_display = scrapy.Field()
    test_camera = scrapy.Field()
    test_loudspeaker = scrapy.Field()
    audio_quality = scrapy.Field()
    battery_life = scrapy.Field()

